### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by nottrynamakeagithubaccount** [jojo989/menuBG-customizer#10]
Yo so I've been trying but couldnt make this mod work. I put the image I wanted in the resources folder, gd appdata folder, and the mods folder but none worked. The hide gd logo setting works too, so it's not on geode's end. Any idea what I could be doing wrong?

**Comment by Cosmo304** [comment]
Same. The mod didn't have lots of info about how to use it, just said to name the file "Background"

**Comment by jojo989** [comment]
just press on the  "pencil" button in the mod info tab and put the photo there

**Comment by jojo989** [comment]
nvm geode doesnt have this button anym0re

**Comment by Imshinora** [comment]
Same guys

**Comment by Hanifinio** [comment]
I'm pretty sure you put it in the config folder although I haven't tried this mod yet

**Comment by jojo989** [comment]
i updated the mod and now   you need to put the image in the mods settings folder

**Comment by Kurokure19** [comment]
It still doesn't work for me for some reason. I put the image (correct name and format) into the settings folder, and it did aboslutely nothing, the "remove logo" works tho.

**Comment by jojo989** [comment]
https://github.com/jojo989/menuBG-customizer/issues/5#issuecomment-2274854515 try putting the image like this, im sorry for making this so confusing for android :c

**Comment by MrKareem1980** [comment]
@jojo989 its working now !!!
Thanks So Much!!
![Screenshot_20240811-024642](https://github.com/user-attachments/assets/c029eb6e-a2a0-483d-a033-94f6e95b330d)
tutorial:
![Screenshot_20240811-031924](https://github.com/user-attachments/assets/a876e797-05ec-40d5-b337-38bc269af577)

**Comment by Kurokure19** [comment]
No idea why it doesn't work tho. Also sorry for the confusion but i use PC btw
![Screenshot 2024-08-11 110504](https://github.com/user-attachments/assets/eaee75a8-0663-45b0-88ae-89e3a4cfa793)


> [#5 (comment)](https://github.com/jojo989/menuBG-customizer/issues/5#issuecomment-2274854515) try putting the image like this, im sorry for making this so confusing for android :c

**Comment by Hanifinio** [comment]
> No idea why it doesn't work tho. Also sorry for the confusion but i use PC btw ![Screenshot 2024-08-11 110504](https://private-user-images.githubusercontent.com/171060758/356863337-eaee75a8-0663-45b0-88ae-89e3a4cfa793.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNzYyMjUsIm5iZiI6MTcyMzM3NTkyNSwicGF0aCI6Ii8xNzEwNjA3NTgvMzU2ODYzMzM3LWVhZWU3NWE4LTA2NjMtNDViMC04OGFlLTg5ZTNhNGNmYTc5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxMTMyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTI5OTBhZDM5NzU5NzQyMGU3ZDc5YWJkODljYzMxNzFlNTRjZGQxY2E0ODczMjllMDMwYjM4NjhjNDMzYTkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yFVzAdeHjdlkGzh2RrR71_0wl8hiHjyJ-Z9cM8zrLB0)
> 
> > [#5 (comment)](https://github.com/jojo989/menuBG-customizer/issues/5#issuecomment-2274854515) try putting the image like this, im sorry for making this so confusing for android :c

Maybe because of Geodify. Try disabling changing the menu screen in its settings

**Comment by Kurokure19** [comment]
> > No idea why it doesn't work tho. Also sorry for the confusion but i use PC btw ![Screenshot 2024-08-11 110504](https://private-user-images.githubusercontent.com/171060758/356863337-eaee75a8-0663-45b0-88ae-89e3a4cfa793.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNzYyMjUsIm5iZiI6MTcyMzM3NTkyNSwicGF0aCI6Ii8xNzEwNjA3NTgvMzU2ODYzMzM3LWVhZWU3NWE4LTA2NjMtNDViMC04OGFlLTg5ZTNhNGNmYTc5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxMTMyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTI5OTBhZDM5NzU5NzQyMGU3ZDc5YWJkODljYzMxNzFlNTRjZGQxY2E0ODczMjllMDMwYjM4NjhjNDMzYTkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yFVzAdeHjdlkGzh2RrR71_0wl8hiHjyJ-Z9cM8zrLB0)
> > > [#5 (comment)](https://github.com/jojo989/menuBG-customizer/issues/5#issuecomment-2274854515) try putting the image like this, im sorry for making this so confusing for android :c
> 
> Maybe because of Geodify. Try disabling changing the menu screen in its settings

bruh i didn't even install Geodify. My menu screen just automatically became like that after the 2.206 update from Rob.

**Comment by Hanifinio** [comment]
That's impossible. That image comes from the Geode website and Rob never added that. You have to have something putting it there. It looks like you have BetterMenu. Check if there's a setting I  there

**Comment by Kurokure19** [comment]
> That's impossible. That image comes from the Geode website and Rob never added that. You have to have something putting it there. It looks like you have BetterMenu. Check if there's a setting I there

That's the problem. Thanks a lot!

**Comment by Hanifinio** [comment]
Your welcome :D
