### ISSUE TITLE
Missing Texture when I place the image

### ISSUE THREAD

**Issue by Miauu-u** [jojo989/menuBG-customizer#17]
When I placed the image I got a "Missing Texture" instead of the image itself, I don't know if it is the resolution in which I have the image (1,280 × 720) I need help :'v
![image](https://github.com/user-attachments/assets/e1094472-bad1-4e24-bcc9-8055dd24b5b9)

**Comment by jojo989** [comment]
whats the extension of the inage? it should be png or jpg

**Comment by Miauu-u** [comment]
> whats the extension of the inage? it should be png or jpg

png, I tried with jpg but it didn't work

**Comment by jojo989** [comment]
can you send me the image

**Comment by Miauu-u** [comment]
> can you send me the image

![image](https://github.com/user-attachments/assets/7f96429e-36e8-4683-b5f6-c3c2c2a055d3)
The selected image is the one that worked for me (the png) and the second is the one that didn't work for me, (jpg) but the png I get the missing texture

**Comment by Miauu-u** [comment]
> can you send me the image

if you want the "background" image here you go
![background](https://github.com/user-attachments/assets/d79f4531-f56d-4308-a62b-e3b6970571fb)

**Comment by jojo989** [comment]
the image should be located here: GeometryDash\geode\mods\jojo989.main_menu_bg_customizer (PC)
![imagen](https://github.com/user-attachments/assets/444ab9c7-978a-4bf4-adb6-b1fb31fdef3b)

**Comment by Miauu-u** [comment]
> GeometryDash\geode\mods\jojo989.main_menu_bg_customizer

![image](https://github.com/user-attachments/assets/6f1c4d4a-449f-465a-95c9-4221f32382d9)
i cant see anything there :<

**Comment by jojo989** [comment]
im sorry i meant AppData\Local\GeometryDash\geode\mods\jojo989.main_menu_bg_customizer\

**Comment by Miauu-u** [comment]
> im sorry i meant AppData\Local\GeometryDash\geode\mods\jojo989.main_menu_bg_customizer\

![image](https://github.com/user-attachments/assets/953296bb-0e34-4ee4-a79e-986dae64de03)
i do that but still give me the same error

**Comment by Miauu-u** [comment]
i will try with another image, to see if works

**Comment by Miauu-u** [comment]
good and bad news, it works but it doesn't work with the image I want :')
![image](https://github.com/user-attachments/assets/56e48631-34e8-4e99-b85d-b1c538f06f77)

**Comment by jojo989** [comment]
huuh, sad :c
