### ISSUE TITLE
BG on more menu screens

### ISSUE THREAD

**Issue by GhostXan** [jojo989/menuBG-customizer#2]
make the background appear not only on the main menu
if possible, make it appear on like, online menu, level menu, main levels menu, level list menu, etc.
that would be so cool :)
great mod btw

**Comment by jojo989** [comment]
yeah i will add support of these menus!

**Comment by jojo989** [comment]
hey! i tried to add it but it seems to crash to a lot of people, you can try to download it in releases tho
