### ISSUE TITLE
crash on exiting Geode menu after enabling "hide GD logo"

### ISSUE THREAD

**Issue by sphericle** [jojo989/menuBG-customizer#7]
![image_2024-05-01_193731309](https://github.com/jojo989/menuBG-customizer/assets/86196223/e1b36319-42db-480b-985e-e44c1536d208)

**Comment by jojo989** [comment]
i think the "geometry dash" mod is making conflict, remove it idk

**Comment by sphericle** [comment]
lol aight i don’t use that anyway
